# When we push SNAPSHOT images, the old SNAPSHOT to be untagged image. We remove
# those untagged images by using this workflow.

name: Remove untagged images

on:
  schedule:
    # UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  remove-untagged-container-images:
    runs-on: ubuntu-latest

    steps:

      - name: Remove untagged container images
        uses: camargo/delete-untagged-action@v1
        with:
          github-token: ${{ secrets.CR_PAT }}
          package-name: untagged-image-test
          personal-account: true
